// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyShowsLibraryProject.Infrastructure.Data;

#nullable disable

namespace MyShowsLibraryProject.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240324120134_Admin-And-User-Added")]
    partial class AdminAndUserAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2c2c1h4e-3t6e-556f-86af-487y56fd2410",
                            ConcurrencyStamp = "84ac1574-f546-47f1-956b-e83c47494a97",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ReviewId");

                    b.HasIndex("SeriesId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e656345-a56d-4543-a7c6-4556d32d4db2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43d9c8da-4d5f-4590-a168-fb3521e8ed7c",
                            Email = "admin1@abv.bg",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN1@ABV.BG",
                            NormalizedUserName = "ADMIN1@ABV.BG",
                            PasswordHash = "AQAAAAEAACcQAAAAEBWBYS3nUYd3hAJo2inq9uvLbuEPG8srHoMuzIuP47lxb3wyY5T+7WGwt5eqFp5GaQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3b75a223-d4ce-4521-af35-7af08fad4151",
                            TwoFactorEnabled = false,
                            UserName = "admin1@abv.bg"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8e656345-a56d-4543-a7c6-4556d32d4db2",
                            RoleId = "2c2c1h4e-3t6e-556f-86af-487y56fd2410"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Crew", b =>
                {
                    b.Property<int>("CrewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Crew identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrewId"), 1L, 1);

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Crew biography");

                    b.Property<string>("Birthdate")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasComment("Crew birthdate");

                    b.Property<string>("MoreInfo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Crew link for more biography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Crew name");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Crew nationality");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Crew picture link");

                    b.Property<string>("Pseudonyms")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Crew pseudonym");

                    b.HasKey("CrewId");

                    b.ToTable("Crews");

                    b.HasComment("Shows crew");

                    b.HasData(
                        new
                        {
                            CrewId = 1,
                            Biography = "David Benioff was born on September 25, 1970 in New York City, New York, USA. He is a producer and writer, known for Game of Thrones (2011) , The Kite Runner (2007) and The 25th Hour (2002) . He has been married to Amanda Peet since September 30, 2006. They have three children.",
                            Birthdate = "25 Sep 1970",
                            MoreInfo = "https://en.wikipedia.org/wiki/David_Benioff",
                            Name = "David Benioff",
                            Nationality = "USA",
                            PictureUrl = "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/289653_v9_bc.jpg",
                            Pseudonyms = ""
                        },
                        new
                        {
                            CrewId = 2,
                            Biography = " whiz-kid with special effects, Robert is from the Spielberg camp of film-making (Steven Spielberg produced many of his films). Usually working with writing partner Bob Gale, Robert's earlier films show he has a talent for zany comedy (Romance of the Stone (1984), 1941 (1979)) and special effect vehicles (Who Drove Roger Rabbit? (1988) and Back to the Future ( 1985)). His later films have become more serious, with the hugely successful Tom Hanks vehicle Forrest Gump (1994) and the Jodie Foster film Contact (1997), both critically acclaimed movies. Again, these films incorporate stunning effects. Robert has proven he can work a serious story around great effects.",
                            Birthdate = "14 May 1952",
                            MoreInfo = "https://en.wikipedia.org/wiki/Robert_Zemeckis",
                            Name = "Robert Zemeckis",
                            Nationality = "USA",
                            PictureUrl = "https://m.media-amazon.com/images/M/MV5BMTgyMTMzMDUyNl5BMl5BanBnXkFtZTcwODA0ODMyMw@@._V1_.jpg",
                            Pseudonyms = "Bob"
                        },
                        new
                        {
                            CrewId = 3,
                            Biography = "Michael J. Fox was born Michael Andrew Fox on June 9, 1961 in Edmonton, Alberta, Canada, to Phyllis Fox (née Piper), a payroll clerk, and William Fox. His parents moved their 10-year-old son, his three sisters, Kelli Fox, Karen, and Jacki, and his brother Steven, to Vancouver, British Columbia, after his father, a sergeant in the Canadian Army Signal Corps, retired. During these years Michael developed his desire to act. At 15 he successfully auditioned for the role of a 10-year-old in a series called Leo and Me (1978). Gaining attention as a bright new star in Canadian television and movies, Michael realized his love for acting when he appeared on stage in \"The Shadow Box.\" At 18 he moved to Los Angeles and was offered a few television-series roles, but soon they stopped coming and he was surviving on boxes of macaroni and cheese. Then his agent called to tell him that he got the part of Alex P. Keaton on the situation comedy Family Ties (1982). He starred in the feature films The Wolf (1985), High School U.S.A. (1983), Poison Ivy (1985) and Back to the Future (1985).",
                            Birthdate = "09 Jun 1961",
                            MoreInfo = "https://en.wikipedia.org/wiki/Michael_J._Fox",
                            Name = "Michael J. Fox",
                            Nationality = "Canadian",
                            PictureUrl = "https://cdn.britannica.com/33/130633-050-DA6DF1CF/Michael-J-Fox-activist.jpg",
                            Pseudonyms = "Mike"
                        },
                        new
                        {
                            CrewId = 4,
                            Biography = "Kit Harington was born Christopher Catesby Harington in Acton, London, to Deborah Jane (Catesby), a former playwright, and David Richard Harington, a businessman. His mother named him after 16th-century British playwright and poet Christopher Marlowe, whose first name was shortened to Kit, a name Harington prefers. Harington's uncle is Sir Nicholas John Harington, the 14th Baronet Harington, and his paternal great-grandfather was Sir Richard Harington, the 12th Baronet Harington. Through his paternal grandmother, Lavender Cecilia Denny, Kit's eight times great-grandfather was King Charles II of England. Also through his father, Harington descends from politician Henry Dundas, 1st Viscount Melville, the bacon merchant T. A. Denny, clergyman Baptist Wriothesley Noel, merchant and politician Peter Baillie, peer William Legge, 4th Earl of Dartmouth, and MP Sir William Molesworth, 6th Baronet.",
                            Birthdate = "26 Dec 1986",
                            MoreInfo = "https://en.wikipedia.org/wiki/Kit_Harington",
                            Name = "Kit Harington",
                            Nationality = "English",
                            PictureUrl = "https://hips.hearstapps.com/harpersbazaaruk.cdnds.net/15/37/original/original-kit-sq-jpg-68954c3a.jpg?resize=980:*",
                            Pseudonyms = ""
                        },
                        new
                        {
                            CrewId = 5,
                            Biography = "George R.R. Martin is an American novelist and short-story writer in the fantasy, horror, and science fiction genres, a screenwriter, and television producer. He is known for his international bestselling series of epic fantasy novels, A Song of Ice and Fire, which was later adapted into the HBO dramatic series Игра на тронове (2011).Martin serves as the series' co-executive producer, and also scripted four episodes of the series. In 2005, Lev Grossman of Time called Martin \"the American Tolkien\".",
                            Birthdate = "20 Sep 1948",
                            MoreInfo = "https://en.wikipedia.org/wiki/George_R._R._Martin",
                            Name = "George R.R. Martin",
                            Nationality = "USA",
                            PictureUrl = "https://miro.medium.com/v2/resize:fit:7800/1*v0RCTUY4rmOHvBH2vCNBcQ.jpeg",
                            Pseudonyms = ""
                        },
                        new
                        {
                            CrewId = 6,
                            Biography = "Bob Gale is an Oscar-nominated screenwriter-producer-director, best known as co-creator, co-writer and co-producer of Back to the Future (1985) and its sequels. Gale was born and raised in St. Louis, Missouri, and graduated Phi Beta Kappa with a B.A. in Cinema from the University of Southern California in 1973. He has written over 30 screenplays; his other film credits include 1941 (1979), I Want to Hold Your Hand (1978), Old Cars (1980), Foreign Property (1992) and Highway 60 (2002), the latter which he directed. In addition to writing movies and occasionally television, Gale has written comic books including Spider-Man, Batman and the IDW Back to the Future title, thus proving to his father that he did not waste hours and hours reading comics in his youth. He has also served as an expert witness in over 25 plagiarism cases, even though this has occasionally required him to wear a suit and tie (oh, the horror!). When he's not in production, writing, shooting off his mouth or wasting time on the internet, he actually does take out the trash even when his wife doesn't ask. Well, sometimes he does...",
                            Birthdate = "25 May 1951",
                            MoreInfo = "https://en.wikipedia.org/wiki/Bob_Gale",
                            Name = "Bob Gale",
                            Nationality = "USA",
                            PictureUrl = "https://images.squarespace-cdn.com/content/v1/5c62c09c4d546e27dc1016c7/1610218958633-L970L7NUPENE6D2M1DUW/107_bob.jpg",
                            Pseudonyms = ""
                        });
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.CrewRole", b =>
                {
                    b.Property<int>("CrewId")
                        .HasColumnType("int")
                        .HasComment("Crew identifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasComment("Role identifier");

                    b.HasKey("CrewId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("CrewRole");

                    b.HasData(
                        new
                        {
                            CrewId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            CrewId = 1,
                            RoleId = 4
                        },
                        new
                        {
                            CrewId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            CrewId = 2,
                            RoleId = 4
                        },
                        new
                        {
                            CrewId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            CrewId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            CrewId = 3,
                            RoleId = 4
                        },
                        new
                        {
                            CrewId = 4,
                            RoleId = 4
                        },
                        new
                        {
                            CrewId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            CrewId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            CrewId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            CrewId = 5,
                            RoleId = 4
                        },
                        new
                        {
                            CrewId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            CrewId = 6,
                            RoleId = 4
                        },
                        new
                        {
                            CrewId = 6,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Episode", b =>
                {
                    b.Property<int>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EpisodeId"), 1L, 1);

                    b.Property<int>("EpisodeNumeration")
                        .HasColumnType("int")
                        .HasComment("Number of the episode in the season");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Url for the episode poster");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasComment("Episode release date");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasComment("Season identifier");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("int")
                        .HasComment("Number of season");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Episode summary");

                    b.HasKey("EpisodeId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episodes");

                    b.HasComment("Season episode");

                    b.HasData(
                        new
                        {
                            EpisodeId = 1,
                            EpisodeNumeration = 1,
                            PosterUrl = "https://static.hbo.com/content/dam/hbodata/series/game-of-thrones/video-stills/season-01/game-of-thrones-season-1-episode-1-full-stitched-607175_PRO35_10-1920.jpg",
                            ReleaseDate = "18 Apr 2011",
                            SeasonId = 1,
                            SeasonNumber = 1,
                            Summary = "Eddard Stark is torn between his family and an old friend when asked to serve at the side of King Robert Baratheon,And in the other side of the world Viserys Targaryen plans to wed his sister to a nomadic warlord in exchange for an army."
                        },
                        new
                        {
                            EpisodeId = 2,
                            EpisodeNumeration = 2,
                            PosterUrl = "https://cdn.vox-cdn.com/thumbor/hPCyBds5DKp5JcmzCgiBrQrQdi4=/0x0:1280x720/1600x900/cdn.vox-cdn.com/uploads/chorus_image/image/46094226/Jon_snow.0.jpg",
                            ReleaseDate = "25 Apr 2011",
                            SeasonId = 1,
                            SeasonNumber = 1,
                            Summary = "While Bran recovers from his fall, Ned takes only his daughters to King's Landing. Jon Snow goes with his uncle Benjen to the Wall. Tyrion joins them."
                        },
                        new
                        {
                            EpisodeId = 3,
                            EpisodeNumeration = 3,
                            PosterUrl = "https://images.cdn.prd.api.discomax.com/2023/02/15/a2ca6975-7063-3bc0-a74a-634b49b97d74.jpeg?f=jpg&q=75&w=1280",
                            ReleaseDate = "1 May 2011",
                            SeasonId = 1,
                            SeasonNumber = 1,
                            Summary = "Jon begins his training with the Night's Watch; Ned confronts his past and future at King's Landing; Daenerys finds herself at odds with Viserys."
                        },
                        new
                        {
                            EpisodeId = 4,
                            EpisodeNumeration = 4,
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTMwNDQ0MTIyMl5BMl5BanBnXkFtZTcwODkxMzkxNA@@._V1_.jpg",
                            ReleaseDate = "08 May 2011",
                            SeasonId = 1,
                            SeasonNumber = 1,
                            Summary = "Eddard investigates Jon Arryn's murder. Jon befriends Samwell Tarly, a coward who has come to join the Night's Watch."
                        },
                        new
                        {
                            EpisodeId = 5,
                            EpisodeNumeration = 5,
                            PosterUrl = "https://static.wikia.nocookie.net/gameofthrones/images/4/48/Thrones_S01E05.jpg/revision/latest?cb=20220918160258",
                            ReleaseDate = "15 May 2011",
                            SeasonId = 1,
                            SeasonNumber = 1,
                            Summary = "Catelyn has captured Tyrion and plans to bring him to her sister, Lysa Arryn, at the Vale, to be tried for his, supposed, crimes against Bran. Robert plans to have Daenerys killed, but Eddard refuses to be a part of it and quits."
                        },
                        new
                        {
                            EpisodeId = 6,
                            EpisodeNumeration = 6,
                            PosterUrl = "https://cdn.vox-cdn.com/thumbor/MKfDGE4yoWdp_x39u5yQyjaCjbw=/0x0:1920x1080/1400x1050/filters:focal(848x506:1154x812):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/56051735/a_golden_crown_1920.0.jpg",
                            ReleaseDate = "22 May 2011",
                            SeasonId = 1,
                            SeasonNumber = 1,
                            Summary = "While recovering from his battle with Jaime, Eddard is forced to run the kingdom while Robert goes hunting. Tyrion demands a trial by combat for his freedom. Viserys is losing his patience with Drogo."
                        },
                        new
                        {
                            EpisodeId = 7,
                            EpisodeNumeration = 7,
                            PosterUrl = "https://static.wikia.nocookie.net/gameofthrones/images/7/79/Daenerys_and_Jorah_2x08.jpg/revision/latest/scale-to-width-down/560?cb=20120524205729",
                            ReleaseDate = "29 May 2011",
                            SeasonId = 1,
                            SeasonNumber = 1,
                            Summary = "Robert has been injured while hunting and is dying. Jon and the others finally take their vows to the Night's Watch. A man, sent by Robert, is captured for trying to poison Daenerys. Furious, Drogo vows to attack the Seven Kingdoms."
                        },
                        new
                        {
                            EpisodeId = 8,
                            EpisodeNumeration = 8,
                            PosterUrl = "https://static.wikia.nocookie.net/gameofthrones/images/0/0c/Thrones_S01E08.jpg/revision/latest?cb=20220918160919",
                            ReleaseDate = "05 Jun 2011",
                            SeasonId = 1,
                            SeasonNumber = 1,
                            Summary = "The Lannisters press their advantage over the Starks; Robb rallies his father's northern allies and heads south to war; The White Walkers attack the Wall; Tyrion returns to his father with some new friends."
                        },
                        new
                        {
                            EpisodeId = 9,
                            EpisodeNumeration = 9,
                            PosterUrl = "https://jackandthegeekstalk.files.wordpress.com/2017/08/maxresdefault-7.jpg?w=1080",
                            ReleaseDate = "12 Jun 2011",
                            SeasonId = 1,
                            SeasonNumber = 1,
                            Summary = "Robb goes to war against the Lannisters. Jon finds himself struggling on deciding if his place is with Robb or the Night's Watch. Drogo has fallen ill from a fresh battle wound. Daenerys is desperate to save him."
                        },
                        new
                        {
                            EpisodeId = 10,
                            EpisodeNumeration = 10,
                            PosterUrl = "https://s1.dmcdn.net/v/GQYpO1ZeIODLfiWno/x1080",
                            ReleaseDate = "19 Jun 2011",
                            SeasonId = 1,
                            SeasonNumber = 1,
                            Summary = "Robb vows to get revenge on the Lannisters. Jon must officially decide if his place is with Robb or the Night's Watch. Daenerys says her final goodbye to Drogo."
                        });
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Genre identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Genre name");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasComment("Shows genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreId = 5,
                            Name = "Horror"
                        },
                        new
                        {
                            GenreId = 6,
                            Name = "Mystery"
                        },
                        new
                        {
                            GenreId = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            GenreId = 8,
                            Name = "Thriller"
                        },
                        new
                        {
                            GenreId = 9,
                            Name = "Western"
                        },
                        new
                        {
                            GenreId = 10,
                            Name = "Adventure"
                        },
                        new
                        {
                            GenreId = 11,
                            Name = "Sci-Fi"
                        });
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"), 1L, 1);

                    b.Property<string>("DateOfRelease")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasComment("Movie release date");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasComment("Movie runtime");

                    b.Property<string>("ForMoreSummaryUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("URL for more info");

                    b.Property<string>("OriginalAudioLanguage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Movie original lenguage");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Movie poster URL");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Movie summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Movie title");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Movie trailer URL");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasComment("Movie model");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            DateOfRelease = "03 Jul 1985",
                            Duration = 116,
                            ForMoreSummaryUrl = "https://en.wikipedia.org/wiki/Back_to_the_Future",
                            OriginalAudioLanguage = "English",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Back_to_the_Future.jpg/220px-Back_to_the_Future.jpg",
                            Summary = "Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.",
                            Title = "Back to the Future",
                            TrailerUrl = "https://www.youtube.com/embed/qvsgGtivCgs?si=fc5W3Tjq1xSBOYoZ&amp"
                        });
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.MovieCrew", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasComment("Movie identifier");

                    b.Property<int>("CrewId")
                        .HasColumnType("int")
                        .HasComment("Crew identifier");

                    b.HasKey("MovieId", "CrewId");

                    b.HasIndex("CrewId");

                    b.ToTable("MoviesCrews");

                    b.HasComment("Movie crew");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CrewId = 2
                        },
                        new
                        {
                            MovieId = 1,
                            CrewId = 3
                        },
                        new
                        {
                            MovieId = 1,
                            CrewId = 6
                        });
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.MovieGenre", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasComment("Movie identifier");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasComment("Genre identifier");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MoviesGenres");

                    b.HasComment("Movie genres");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = 10
                        },
                        new
                        {
                            MovieId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 1,
                            GenreId = 11
                        });
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.MovieReview", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasComment("Movie identifier");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasComment("Review identifier");

                    b.HasKey("MovieId", "ReviewId");

                    b.HasIndex("ReviewId");

                    b.ToTable("MoviesReviews");

                    b.HasComment("Movie reviews");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Review identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Review content");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasComment("Rating given to the movie");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasComment("Review model");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Role identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Role name");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasComment("Crew role in the show");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Director"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Writer"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Actor"
                        },
                        new
                        {
                            RoleId = 4,
                            Name = "Producer"
                        },
                        new
                        {
                            RoleId = 5,
                            Name = "Music Composer"
                        },
                        new
                        {
                            RoleId = 6,
                            Name = "Cinematographer"
                        },
                        new
                        {
                            RoleId = 7,
                            Name = "Editor"
                        },
                        new
                        {
                            RoleId = 8,
                            Name = "ArtDirector"
                        },
                        new
                        {
                            RoleId = 9,
                            Name = "CostumeDesigner"
                        });
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Season identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonId"), 1L, 1);

                    b.Property<string>("EpisodesInSeason")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("Number of episodes in the season");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Url for the season poster");

                    b.Property<int>("SeasonNumberation")
                        .HasColumnType("int")
                        .HasComment("Season numberation");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int")
                        .HasComment("Serie identifier");

                    b.Property<string>("YearOfRelease")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasComment("The year saeson is released");

                    b.HasKey("SeasonId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Seasons");

                    b.HasComment("Show season");

                    b.HasData(
                        new
                        {
                            SeasonId = 1,
                            EpisodesInSeason = "10",
                            PosterUrl = "https://static.posters.cz/image/1300/posters/game-of-thrones-season-1-key-art-i161816.jpg",
                            SeasonNumberation = 1,
                            SeriesId = 1,
                            YearOfRelease = "2011"
                        });
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Serie", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Serie identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeriesId"), 1L, 1);

                    b.Property<string>("ForMoreSummaryUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("URL for more info");

                    b.Property<string>("OriginalAudioLanguage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Serie original language");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Serie poster URL");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Serie summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Serie title");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Serie trailer URL");

                    b.Property<string>("YearOfEnd")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasComment("Series end year");

                    b.Property<string>("YearOfStart")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasComment("Serie start year");

                    b.HasKey("SeriesId");

                    b.ToTable("Series");

                    b.HasComment("Serie model");

                    b.HasData(
                        new
                        {
                            SeriesId = 1,
                            ForMoreSummaryUrl = "https://en.wikipedia.org/wiki/Game_of_Thrones",
                            OriginalAudioLanguage = "English",
                            PosterUrl = "https://i.pinimg.com/originals/ac/4f/fd/ac4ffd8309980a091dd1dc57abe908b4.jpg",
                            Summary = "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for a millennia.",
                            Title = "Game of Thrones",
                            TrailerUrl = "https://www.youtube.com/embed/bjqEWgDVPe0?si=1az-pQmunA3VvNlG",
                            YearOfEnd = "2019",
                            YearOfStart = "2011"
                        });
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.SerieCrew", b =>
                {
                    b.Property<int>("SerieId")
                        .HasColumnType("int")
                        .HasComment("Serie identifier");

                    b.Property<int>("CrewId")
                        .HasColumnType("int")
                        .HasComment("Crew identifier");

                    b.HasKey("SerieId", "CrewId");

                    b.HasIndex("CrewId");

                    b.ToTable("SeriesCrews");

                    b.HasComment("Serie crew");

                    b.HasData(
                        new
                        {
                            SerieId = 1,
                            CrewId = 1
                        },
                        new
                        {
                            SerieId = 1,
                            CrewId = 4
                        },
                        new
                        {
                            SerieId = 1,
                            CrewId = 5
                        });
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.SerieGenre", b =>
                {
                    b.Property<int>("SerieId")
                        .HasColumnType("int")
                        .HasComment("Serie identifier");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasComment("Genre identifier");

                    b.HasKey("SerieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("SeriesGenres");

                    b.HasComment("Serie genres");

                    b.HasData(
                        new
                        {
                            SerieId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            SerieId = 1,
                            GenreId = 10
                        },
                        new
                        {
                            SerieId = 1,
                            GenreId = 3
                        });
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.SerieReview", b =>
                {
                    b.Property<int>("SerieId")
                        .HasColumnType("int")
                        .HasComment("Serie identifier");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasComment("Review identitfier");

                    b.HasKey("SerieId", "ReviewId");

                    b.HasIndex("ReviewId");

                    b.ToTable("SeriesReviews");

                    b.HasComment("Serie reviews");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.UserMovie", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User identifier");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasComment("Movie identifier");

                    b.HasKey("UserId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("UsersMovies");

                    b.HasComment("User movies");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.UserReview", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User identifier");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasComment("Review identifier");

                    b.HasKey("UserId", "ReviewId");

                    b.HasIndex("ReviewId");

                    b.ToTable("UsersReviews");

                    b.HasComment("User reviews");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.UserSerie", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User identifier");

                    b.Property<int>("SerieId")
                        .HasColumnType("int")
                        .HasComment("Serie identifier");

                    b.HasKey("UserId", "SerieId");

                    b.HasIndex("SerieId");

                    b.ToTable("UsersSeries");

                    b.HasComment("User series");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Movie", null)
                        .WithMany("UserMovies")
                        .HasForeignKey("MovieId");

                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Review", null)
                        .WithMany("UserReviews")
                        .HasForeignKey("ReviewId");

                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Serie", null)
                        .WithMany("UserSerie")
                        .HasForeignKey("SeriesId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.CrewRole", b =>
                {
                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Crew", "Crew")
                        .WithMany("Roles")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Role", "Role")
                        .WithMany("CrewRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Episode", b =>
                {
                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.MovieCrew", b =>
                {
                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Crew", "Crew")
                        .WithMany("MovieCrew")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Movie", "Movie")
                        .WithMany("MovieCrews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.MovieGenre", b =>
                {
                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.MovieReview", b =>
                {
                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Movie", "Movie")
                        .WithMany("MovieReviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Review", "Review")
                        .WithMany("MovieReviews")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Season", b =>
                {
                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Serie", "Serie")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.SerieCrew", b =>
                {
                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Crew", "Crew")
                        .WithMany("SerieCrew")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Serie", "Serie")
                        .WithMany("SerieCrews")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.SerieGenre", b =>
                {
                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Genre", "Genre")
                        .WithMany("SerieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Serie", "Serie")
                        .WithMany("SerieGenres")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.SerieReview", b =>
                {
                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Review", "Review")
                        .WithMany("SerieReviews")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Serie", "Serie")
                        .WithMany("SerieReviews")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.UserMovie", b =>
                {
                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.UserReview", b =>
                {
                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.UserSerie", b =>
                {
                    b.HasOne("MyShowsLibraryProject.Infrastructure.Data.Models.Serie", "Serie")
                        .WithMany()
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Serie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Crew", b =>
                {
                    b.Navigation("MovieCrew");

                    b.Navigation("Roles");

                    b.Navigation("SerieCrew");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");

                    b.Navigation("SerieGenres");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Movie", b =>
                {
                    b.Navigation("MovieCrews");

                    b.Navigation("MovieGenres");

                    b.Navigation("MovieReviews");

                    b.Navigation("UserMovies");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Review", b =>
                {
                    b.Navigation("MovieReviews");

                    b.Navigation("SerieReviews");

                    b.Navigation("UserReviews");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Role", b =>
                {
                    b.Navigation("CrewRoles");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("MyShowsLibraryProject.Infrastructure.Data.Models.Serie", b =>
                {
                    b.Navigation("Seasons");

                    b.Navigation("SerieCrews");

                    b.Navigation("SerieGenres");

                    b.Navigation("SerieReviews");

                    b.Navigation("UserSerie");
                });
#pragma warning restore 612, 618
        }
    }
}
